# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('header', models.CharField(max_length=100, verbose_name=b'Header')),
                ('header_image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=b'/uploads/', verbose_name=b'Image header')),
                ('thumbnail', easy_thumbnails.fields.ThumbnailerImageField(upload_to=b'/uploads/', verbose_name=b'Thumbnail')),
                ('negative_feedback', models.IntegerField(default=0, verbose_name=b'Negative Feedback count')),
                ('positive_feedback', models.IntegerField(default=0, verbose_name=b'Positive Feedback count')),
                ('article_type', models.CharField(choices=[(b'M', b'Monitoring'), (b'V', b'Visualizing'), (b'P', b'Provisioning'), (b'N', b'Networking'), (b'W', b'Web'), (b'D', b'Deployment'), (b'O', b'Other')], default=b'M', max_length=2, verbose_name=b'Article type')),
                ('content', tinymce.models.HTMLField(verbose_name=b'Article body')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
