version: "3.8"

networks:
  coookit:

services:

  database:
    restart: on-failure
    networks:
      coookit:
        aliases:
          - db-host
    build:
      context: .
      dockerfile: docker/db/Dockerfile
      labels:
        image-name: coookit-db-img
    image: ghcr.io/iakonk/coookit-db-img:latest
    volumes:
      - type: bind
        source: /app/pg_backup
        target: /pg_backup
      - type: bind
        source: /app/pgdata
        target: /var/lib/postgresql/11/main
    environment:
      - PGDATA=/var/lib/postgresql/11/main
      - PGBACKUP=/pg_backup

  web:
    restart: on-failure
    depends_on:
      - database
    networks:
      - coookit
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      labels:
        image: ghcr.io/iakonk/coookit-app-img:latest
      args:
        - DJANGO_SETTINGS_MODULE=coookit.settings
        - UWSGI_CHDIR=/usr/local/lib/python2.7/site-packages/coookit
        - PYTHONPATH=/usr/local/lib/python2.7/site-packages
        - PG_HOST=db-host
        - PG_PORT=<SOME_PORT>
        - PG_USER=<SOME_USER>
        - PG_PASS=<SOME_PASS>
        - PG_DB_NAME=<SOME_NAME>
    image: coookit-app-img
    ports:
        - "127.0.0.1:8888:88888"
    volumes:
      - type: bind
        source: /app/uploads
        target: /app/uploads
